services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    # ports:
      # - 32400:32400   #Default port
      # - 32469:32469   #SSL port
      # - 1900:1900/udp   #DLNA server
      # - 32410:32410/udp   #GDM network discovery
      # - 32412:32412/udp   #GDM network discovery
      # - 32413:32413/udp   #GDM network discovery
      # - 32414:32414/udp   #GDM network discovery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - HOSTNAME=luthor.bi-frost
      # - ADVERTISE_IP=http://192.168.0.125:32400
      - PLEX_CLAIM=claim-aG_m2kTFMkQ1YztW2uPv
    volumes:
      - /media:/media
      - plex_config:/config
      - plex_trasnscode:/transcode
    network_mode: host

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /media:/media
      - sonarr_config:/config
  
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - tautulli_config:/config

volumes:
  plex_config:
  
  plex_trasnscode:

  sonarr_config:
  
  tautulli_config: