services:
  plex:
    container_name: plex
    image: linuxserver/plex:latest
    restart: unless-stopped
    ports:
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - HOSTNAME=luthor.bi-frost.local
      - PLEX_CLAIM=claim-DxREnAAz9H8KJLGgeTn9
    volumes:
      - /rust/media:/data
      - plex_config:/config
      - plex_trasnscode:/transcode
  
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /rust/media:/data
      - sonarr_config:/config
  
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli:latest
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - tautulli_config:/config

volumes:
  plex_config:
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=127.0.0.1,rw"
      device: ":/rust/nfs/container-vols/plex_config"
  
  plex_trasnscode:

  sonarr_config:
  
  tautulli_config:
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=127.0.0.1,rw"
      device: ":/rust/nfs/container-vols/tautulli_config"